new
	self error: 'Use #repository:credentials:'